// Fill out your copyright notice in the Description page of Project Settings.


#include "Weapon/Gun/Shotgun.h"

#include "NiagaraFunctionLibrary.h"
#include "Controllers/FpsWaveCharacterController.h"
#include "HUD/Crosshair.h"
#include "Kismet/GameplayStatics.h"


// Sets default values
AShotgun::AShotgun()
{
	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	AttackDelay = 0.8f;
	ReloadSpeed = 3.f;
	MaxBulletCount = 8;
	MaxAccuracy = 100.f;
	MinAccuracy = 20.f;
	CurrentAccuracy = 60.f;
	MaxSpreadAngle = 5.f;
	MinSpreadAngle = 3.f;
	AccuracyDecreasePerShot = (MaxAccuracy - MinAccuracy) / MaxBulletCount;
	BulletPerShot = 8;
	SpreadStartDistance = 100.f;
}

// Called when the game starts or when spawned
void AShotgun::BeginPlay()
{
	Super::BeginPlay();
}

void AShotgun::Attack()
{
	Super::Attack();
}

void AShotgun::StartAutoFire()
{
	Super::StartAutoFire();
}

void AShotgun::FireSingleBullet()
{
	//todo Accuracy ì¡°ì •
	// íŒŒí‹°í´ ìŠ¤í°
	if (GunFireParticles)
	{
		UNiagaraFunctionLibrary::SpawnSystemAttached(GunFireParticles,
		                                             FirePoint, NAME_None,
		                                             FVector::ZeroVector,
		                                             FRotator::ZeroRotator,
		                                             EAttachLocation::SnapToTargetIncludingScale,
		                                             true);
	}

	if (FireSound)
	{
		UGameplayStatics::PlaySoundAtLocation(GetWorld(), FireSound, this->GetActorLocation());
	}

	if (OnTriggerMontage.IsBound())
	{
		OnTriggerMontage.Broadcast();
	}

	if (!PlayerController)
	{
		if (auto Cont = GetWorld()->GetFirstPlayerController<AFpsWaveCharacterController>())
		{
			PlayerController = Cont;
		}
	}

	//í•„ìˆ˜
	Recoil();

	FVector2D WidgetScreenPosition = FVector2d::ZeroVector;
	if (TObjectPtr<UCrosshair> Crosshair = PlayerController->GetCrosshairObj())
	{
		WidgetScreenPosition = Crosshair->GetAimLocation();
	}

	FVector CrosshairWorldPosition;
	FVector CrosshairWorldDirection;

	// ìŠ¤í¬ë¦° ì¢Œí‘œ â†’ ì›”ë“œ ì¢Œí‘œ/ë°©í–¥ ë³€í™˜
	bool bScreenToWorld = UGameplayStatics::DeprojectScreenToWorld(
		PlayerController,
		WidgetScreenPosition,
		CrosshairWorldPosition,
		CrosshairWorldDirection);

	if (!bScreenToWorld) return;

	FCollisionQueryParams Params;
	Params.AddIgnoredActor(this);
	Params.AddIgnoredActor(GetOwner());


	for (int i = 0; i < BulletPerShot; ++i)
	{
		CurrentAccuracy = FMath::Max(CurrentAccuracy - AccuracyDecreasePerShot, MinAccuracy);
		float NormalizedAccuracy = (CurrentAccuracy - MinAccuracy) / (MaxAccuracy - MinAccuracy);
		float RandomScale = FMath::FRandRange(1.f, 1.4f);
		float SpreadAngleDeg = FMath::Lerp(MaxSpreadAngle, MinSpreadAngle, NormalizedAccuracy) * RandomScale;
		float SpreadAngleRad = FMath::DegreesToRadians(SpreadAngleDeg);

		// === 1ï¸âƒ£ ì¹´ë©”ë¼ ê¸°ì¤€ AimPoint ê³„ì‚° ===
		FVector Start = CrosshairWorldPosition;
		FVector End = Start + CrosshairWorldDirection * 10000.f;

		FHitResult CrosshairHit;
		FVector AimPoint = End;
		if (GetWorld()->LineTraceSingleByChannel(CrosshairHit, Start, End, ECC_Visibility, Params))
		{
			AimPoint = CrosshairHit.ImpactPoint;
		}

		// === 2ï¸âƒ£ ì´êµ¬ ê¸°ì¤€ ë°©í–¥ ê³„ì‚° ===
		FVector MuzzleLocation = FirePoint->GetComponentLocation();
		FVector MuzzleToAim = AimPoint - MuzzleLocation;
		float DistToAim = MuzzleToAim.Size();
		FVector MuzzleToAimDir = MuzzleToAim.GetSafeNormal();

		FVector BeamEndPoint = AimPoint;

		// === 3ï¸âƒ£ í¼ì§ ì‹œì‘ ì „ êµ¬ê°„ ===
		if (DistToAim <= SpreadStartDistance)
		{
			FHitResult Hit;
			if (GetWorld()->LineTraceSingleByChannel(Hit, MuzzleLocation, AimPoint, ECC_Visibility, Params))
			{
				BeamEndPoint = Hit.ImpactPoint;
			}
			else
			{
				BeamEndPoint = AimPoint;
			}
		}
		else
		{
			// === 4ï¸âƒ£ í¼ì§ ì‹œì‘ ì´í›„ ===
			FVector SpreadOrigin = MuzzleLocation + MuzzleToAimDir * SpreadStartDistance;

			// í¼ì§ ì „ êµ¬ê°„ ì¶©ëŒ ì²´í¬
			FHitResult PreSpreadHit;
			if (GetWorld()->LineTraceSingleByChannel(PreSpreadHit, MuzzleLocation, SpreadOrigin, ECC_Visibility, Params))
			{
				BeamEndPoint = PreSpreadHit.ImpactPoint;
			}
			else
			{
				// ğŸ”¥ ìˆ˜ì •: SpreadOriginì—ì„œ ì‹¤ì œ í¼ì§ ì ìš©
				FVector SpreadOriginToAim = (AimPoint - SpreadOrigin).GetSafeNormal();
    
				// SpreadOriginë¶€í„° ë‚¨ì€ ê±°ë¦¬ ê³„ì‚°
				float RemainingDistance = (AimPoint - SpreadOrigin).Size();
				RemainingDistance = FMath::Min(RemainingDistance, 10000.f - SpreadStartDistance);
    
				// í•´ë‹¹ ê±°ë¦¬ì—ì„œì˜ í¼ì§ ë°˜ê²½ ê³„ì‚°
				float SpreadRadius = RemainingDistance * FMath::Tan(SpreadAngleRad);
    
				// ëœë¤ ì˜¤í”„ì…‹ ìƒì„±
				FVector RightVector = FVector::CrossProduct(SpreadOriginToAim, FVector::UpVector).GetSafeNormal();
				if (RightVector.IsNearlyZero())
				{
					RightVector = FVector::CrossProduct(SpreadOriginToAim, FVector::ForwardVector).GetSafeNormal();
				}
				FVector UpVector = FVector::CrossProduct(RightVector, SpreadOriginToAim).GetSafeNormal();
    
				float RandomAngle = FMath::FRandRange(0.f, 2.f * PI);
				float RandomRadius = FMath::Sqrt(FMath::FRand()) * SpreadRadius;
    
				FVector RandomOffset = (RightVector * FMath::Cos(RandomAngle) + UpVector * FMath::Sin(RandomAngle)) * RandomRadius;
    
				// ì¶”ê°€ ëœë¤ì„±
				RandomOffset += FMath::VRand() * SpreadRadius * 0.3f;
    
				// SpreadOriginì—ì„œ ë‚¨ì€ ê±°ë¦¬ë§Œí¼ ë‚˜ì•„ê°„ ì§€ì  + ëœë¤ ì˜¤í”„ì…‹
				FVector SpreadTarget = SpreadOrigin + SpreadOriginToAim * RemainingDistance + RandomOffset;
    
				FHitResult AfterSpreadHit;
				if (GetWorld()->LineTraceSingleByChannel(AfterSpreadHit, SpreadOrigin, SpreadTarget, ECC_Visibility, Params))
				{
					BeamEndPoint = AfterSpreadHit.ImpactPoint;
				}
				else
				{
					BeamEndPoint = SpreadTarget;
				}
			}
		}

		// === 5ï¸âƒ£ ì´í™íŠ¸ ìŠ¤í° ===
		if (GunImpactParticles)
		{
			UGameplayStatics::SpawnEmitterAtLocation(GetWorld(), GunImpactParticles, BeamEndPoint);
		}

		// (ì„ íƒ) ë””ë²„ê·¸ìš©
		DrawDebugLine(GetWorld(), MuzzleLocation, BeamEndPoint, FColor::Red, false, 1.f, 0, 0.5f);
	}
}

void AShotgun::AttackFinished()
{
	Super::AttackFinished();
	CurrentAccuracy = 60.f;
}

void AShotgun::Recoil()
{
	if (!PlayerController)
	{
		if (auto Cont = Cast<AFpsWaveCharacterController>(GetWorld()->GetFirstPlayerController()))
		{
			PlayerController = Cont;      
		}
	}

	float Pitch = FMath::FRandRange(4.0f, 6.f);
	float Yaw = FMath::FRandRange(-3.0f, 3.0f);

	// ëª©í‘œ ë°˜ë™ ì„¤ì •
	TargetRecoilRotation = FRotator(-Pitch, Yaw, 0.f);
	CurrentRecoilRotation = FRotator::ZeroRotator;
	RecoilProgress = 0.f;
	bIsRecoiling = true;
}

float AShotgun::GetAttackDelay()
{
	return AttackDelay;
}

void AShotgun::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (bIsRecoiling)
	{
		// ì§„í–‰ë„ ì—…ë°ì´íŠ¸
		RecoilProgress += DeltaTime / RecoilDuration;
		RecoilProgress = FMath::Clamp(RecoilProgress, 0.f, 1.f);
        
		// ë¶€ë“œëŸ¬ìš´ ë³´ê°„ (ì»¤ë¸Œ ì ìš©)
		float Alpha = FMath::InterpEaseOut(0.f, 1.f, RecoilProgress, 2.0f);
		FRotator NewRecoil = FMath::Lerp(FRotator::ZeroRotator, TargetRecoilRotation, Alpha);
        
		// ì´ì „ í”„ë ˆì„ê³¼ì˜ ì°¨ì´ë§Œ ì ìš©
		FRotator DeltaRecoil = NewRecoil - CurrentRecoilRotation;
        
		PlayerController->AddPitchInput(DeltaRecoil.Pitch);
		PlayerController->AddYawInput(DeltaRecoil.Yaw);
        
		CurrentRecoilRotation = NewRecoil;
        
		// ë°˜ë™ ì™„ë£Œ
		if (RecoilProgress >= 1.f)
		{
			bIsRecoiling = false;
		}
	}
}